"""Headings in official tone (engineer, 2026-10-03: the client asked, on the Design Basis Report, for official topics as
headings). The modules keep writing their original titles; doc.h, doc.chapter, doc.title and doc.sub pass every one
through official(), which keeps the number and swaps the title. The table is also the before/after list for review.
"""
import re

HEADINGS = {
    # front matter and executive summary
    "Abbreviations and definitions": "Abbreviations and Definitions",
    "A note on the term TE": "Note on the Term TE",
    "Executive summary": "Executive Summary",
    "The project area": "Project Area",
    "Data collected": "Data Collection",
    "Design basis": "Design Basis",
    "Population and flows": "Population and Wastewater Flows",
    "Decisions requested": "Decisions Requested",
    "How the options are developed and compared": "Options Development and Evaluation",
    "The sewer network options": "Sewer Network Options",
    "Recommendation": "Recommendations",
    "Deliverables": "Deliverables",
    # 1
    "Project, scope and process": "Project Background and Scope",
    "Introduction and background": "Introduction",
    "Objectives": "Project Objectives",
    "Structure of this report": "Report Structure",
    "The study area": "Study Area",
    "Location and settlements": "Location and Settlements",
    "Boundary": "Project Boundary",
    "Coordinate system": "Coordinate Reference System",
    "Topography and drainage": "Topography and Drainage",
    "Climate": "Climate",
    "Road network": "Road Network",
    "Flood hazard": "Flood Hazard",
    "Programme and design stages": "Programme and Design Stages",
    "Deliverables at the concept stage": "Concept Stage Deliverables",
    "Deliverables of the following stages": "Subsequent Stage Deliverables",
    "Consultation record": "Consultation Record",
    "Decisions requested and matters requiring confirmation": "Decisions and Matters for Confirmation",
    "What is asked of Nama Water Services, and what is adopted": "Register of Decisions and Adopted Values",
    "The decisions requested from Nama Water Services": "Decisions Requested",
    "The values adopted, for information": "Adopted Values",
    "Other matters requiring confirmation": "Other Matters for Confirmation",
    "Data requested": "Data Requests",
    # 2
    "Data": "Data Collection and Assessment",
    "Data collection": "Data Collection",
    "Assessment of the data": "Data Assessment",
    "Wastewater assets": "Wastewater Assets",
    "Potable water network": "Potable Water Network",
    "Electricity accounts": "Electricity Accounts",
    "Cadastral and settlement data": "Cadastral and Settlement Data",
    "Other datasets supplied": "Other Datasets",
    "Survey and investigation": "Surveys and Investigations",
    "Topographic and utility survey": "Topographic and Utility Survey",
    "Terrain model": "Digital Terrain Model",
    "Geotechnical investigation and trial pits": "Geotechnical Investigation and Trial Pits",
    "Existing systems: as-built records and GIS": "As-Built Records and GIS of the Existing Systems",
    # 3
    "Basis of design": "Basis of Design",
    "Codes, standards and departures": "Codes, Standards and Departures",
    "Departures": "Departures from the Guidelines",
    "Level of service and resilience": "Level of Service and Resilience",
    "Design criteria: collection network": "Design Criteria for the Collection Network",
    "Hydraulic formulation": "Hydraulic Formulation",
    "Gradients and self-cleansing at the concept stage": "Pipe Gradients and Self-Cleansing",
    "Depth of cover and pumping": "Depth of Cover and Pumping",
    "Design criteria: treatment plant": "Design Criteria for the Treatment Plant",
    "The flows and loads the plant is sized on": "Design Flows and Loads",
    # 4
    "Demand and flows": "Population, Demand and Wastewater Flows",
    "Population and land use": "Population and Land Use",
    "Approach": "Methodology",
    "The settlements and their boundaries": "Settlements and Settlement Boundaries",
    "From the meters to the properties": "Properties from Electricity Meters",
    "Occupancy rate": "Occupancy Rate",
    "Land use": "Land Use",
    "Capacity of the empty land": "Development Capacity of Vacant Plots",
    "How fast each settlement grows": "Population Growth Rate",
    "When a settlement is full: the overflow": "Settlement Saturation and Population Overflow",
    "The design horizon: 2055, or the year the land is full": "Design Horizon",
    "Where the growth is placed": "Spatial Distribution of Growth",
    "Wastewater generation and design flows": "Wastewater Generation and Design Flows",
    "Water demand": "Water Demand",
    "Special consumption: the industrial estates": "Special Consumption: Industrial Estates",
    "Return to the sewer": "Return to Sewer",
    "The flow from each plot": "Plot Flows",
    "Infiltration": "Infiltration",
    "Peak flow": "Peak Flow",
    "Projection through the design period": "Flow Projection over the Design Period",
    "The flow each element is designed for": "Design Flows by System Element",
    "Non-domestic discharges: industrial estates and identified projects": "Non-Domestic Discharges and Identified Projects",
    "The large-consumer accounts": "Large-Consumer Accounts",
    "Identified projects": "Identified Projects",
    "Treated effluent demand and customers": "Treated Effluent Demand and Customers",
    # 4, minor headings
    "The 126 meters with no plot within 15 metres": "Meters More Than 15 Metres from a Plot",
    "The plot": "Plots",
    "The pipe": "Sewers",
    "The pumping station and its rising main": "Pumping Stations and Rising Mains",
    "The trunk sewers and the treatment plant": "Trunk Sewers and Treatment Plant",
    # 5
    "The existing system": "Existing Wastewater System",
    "Hydraulic assessment of the existing networks": "Hydraulic Assessment of the Existing Networks",
    "Purpose": "Purpose",
    "Model": "Hydraulic Model",
    "Rehabilitation and upgrading": "Rehabilitation and Upgrading",
    "Verification of the Regional Master Plan": "Verification of the Regional Master Plan",
    # 6
    "Options": "Options Development",
    "Options methodology": "Options Methodology",
    "Number and character of the options": "Number and Character of the Options",
    "The approach proposed for each option": "Proposed Approach by Character",
    "Basis of comparison": "Basis of Comparison",
    "Selection": "Selection Criteria",
    "Sewer network options": "Sewer Network Options",
    "Principles": "Design Principles",
    "Corridor constraints": "Corridor Constraints",
    "Network hierarchy": "Network Hierarchy",
    "Early-year operation": "Early-Year Operation",
    "The model": "Hydraulic Model",
    "The seven options": "Description of the Options",
    "Comparison": "Comparison of the Options",
    "When the network becomes self-cleansing": "Self-Cleansing Assessment",
    "Pumping and lifting stations": "Pumping and Lifting Stations",
    "Treated effluent network options": "Treated Effluent Network Options",
    "Treatment plant options": "Treatment Plant Options",
    "Capacity and phasing": "Capacity and Phasing",
    "Process selection": "Process Selection",
    "Siting": "Site Selection",
    "Excess effluent, emergency provisions and tankers": "Excess Effluent, Emergency Provisions and Tanker Reception",
    "Tanker reception": "Tanker Reception",
    "Excess treated effluent": "Excess Treated Effluent",
    "Emergency provisions": "Emergency Provisions",
    "Sludge management strategy": "Sludge Management Strategy",
    # 7
    "Assessment and appraisal": "Technical and Financial Appraisal",
    "Ground conditions": "Ground Conditions",
    "Flood protection": "Flood Risk and Protection",
    "Odour assessment": "Odour Assessment",
    "Climate resilience": "Climate Resilience",
    "Environmental and social assessment": "Environmental and Social Assessment",
    "Utility interfaces and approvals": "Utility Interfaces and Approvals",
    "Records held and required": "Utility Records",
    "Clearances": "Clearances",
    "Trial pits": "Trial Pits",
    "Approvals register": "Approvals Register",
    "Sustainability": "Sustainability",
    "Cost": "Cost Estimate",
    "Basis": "Basis of the Estimate",
    "Scope of the estimate": "Scope of the Estimate",
    "Operating cost": "Operating Cost",
    "Life cycle cost and net present value": "Life-Cycle Cost and Net Present Value",
    "Risk": "Risk Management",
    "Value engineering": "Value Engineering",
    "Comparison and recommendation": "Options Appraisal and Recommendation",
    # 8
    "Delivery": "Project Delivery, Conclusions and Recommendations",
    "Implementation roadmap": "Implementation Roadmap",
    "Contracting strategy": "Contracting Strategy",
    "Project integration": "Project Integration",
    "Conclusions": "Conclusions",
    "Recommendations": "Recommendations",
    "Appendices": "Appendices",
    # appendices
    "Population, land use and flow: the working": "Population, Land Use and Flow Calculations",
    "Electricity meters: tariff to category": "Electricity Tariffs and Consumer Categories",
    "Occupancy rate, properties per plot, home share and capacity by settlement":
        "Settlement Parameters: Occupancy, Properties per Plot, Home Share and Capacity",
    "The overflow routes in full": "Population Overflow Routes",
    "Network options: quantities, pumping stations and depth": "Network Options: Quantities, Pumping Stations and Depth",
    "Design criteria, with references": "Design Criteria and References",
    "Drawings": "Drawings",
    "Sewers and Manholes": "Sewers and Manholes",
}

_NUM = re.compile(r"^((?:Appendix [A-Z]\.|[A-Z]\.\d+(?:\.\d+)*\.|\d+(?:\.\d+)*\.)\s+)(.+)$")


def official(text):
    """'4.1.7.   How fast each settlement grows' -> '4.1.7.   Population Growth Rate'."""
    m = _NUM.match(text)
    prefix, title = (m.group(1), m.group(2)) if m else ("", text)
    return prefix + HEADINGS.get(title, title)
